export * from './system.types';
export * from './obras.types';
export * from './personas.types';
export * from './inmuebles.types';
export * from './finanzas.types';
export * from './cuotas.types';
export * from './padronImport.types';
export * from './planesImport.types';
export * from './dashboard.types';